export const projects = [
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/next_minting_dapp@main/public/assets/1920x600.png",
    name: "Minting_dapp",
    ext: "js",
    lang: "vercel",
    git: "https://github.com/tomiwolf/next_minting_dapp",
    live: "https://boredcreepycapybaras.vercel.app/",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/portfolio-tomiwolf@main/src/assets/loopbit.png",
    name: "Loopbit",
    ext: "app",
    lang: "py",
    git: "https://github.com/tomiwolf/loopbitv1",
    live: "https://www.loopbit.app/",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/rock-paper-scissors@main/public/images/piedrapaeltijera.png",
    name: "Rock-Paper-Scisors",
    ext: "js",
    lang: "js,games",
    git: "https://github.com/tomiwolf/rock-paper-scissors",
    live: "https://rock-paper-scissors-tw.netlify.app/",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/portfolio-tomiwolf@main/src/assets/biolink.png",
    name: "ExBiolink",
    ext: "",
    lang: "personal",
    git: "https://github.com/tomiwolf/portfolio-tomiwolf/blob/main/src/assets/biolink.png",
    live: "https://bio.link/tomiwolf",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/portfolio-tomiwolf@main/src/assets/nftmarketplace.png",
    name: "NFT MARKETPLACE",
    ext: "BSC",
    lang: "js",
    git: "https://github.com/tomiwolf/nft-marketplace-BSC",
    live: "https://nft-marketplace-bsc-testnet.netlify.app/",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/portfolio-tomiwolf@main/src/assets/openseacarpis.png",
    name: "Opensa",
    ext: "Rinkeby",
    lang: "eth",
    git: "https://github.com/tomiwolf/myNFTcollection",
    live: "https://testnets.opensea.io/collection/boredcreppycarpinchos",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/portfolio-tomiwolf@main/src/assets/thewolfgame.png",
    name: "TheWolfGame",
    ext: "Rinkeby",
    lang: "js",
    git: "https://github.com/tomiwolf/thelobogame",
    live: "https://thewolfgame.netlify.app/",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/Piggydapp@main/public/demo2.png",
    name: "Piggys minting Dapp",
    ext: "eth",
    lang: "eth",
    git: "https://github.com/tomiwolf/Piggydapp",
    live: "https://piggydapp.vercel.app/",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/Mint_Tokens_App@main/screenshot.png",
    name: "MintToken-Dapp",
    ext: "eth",
    lang: "eth",
    git: "https://github.com/tomiwolf/Mint_Tokens_App",
    live: "https://minttokensapp.vercel.app/mint-token",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/portfolio-tomiwolf@main/src/assets/awcapital.png",
    name: "Aw-Capital",
    ext: "html",
    lang: "js",
    git: "https://awcapital.netlify.app/",
    live: "https://github.com/tomiwolf/Awcapital2",
  },
  {
    img: "https://cdn.jsdelivr.net/gh/tomiwolf/D-Tasks3.0@main/screenshot.png",
    name: "Task manager 3.0",
    ext: "eth",
    lang: "eth",
    git: "",
    live: "https://editor.p5js.org/smrnjeet222/sketches/T0o5woDT5",
  },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/dumpBox.png",
  //   name: "DumpBox",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/tomiwolf/D-Tasks3.0",
  //   live: "https://github.com/tomiwolf/D-Tasks3.0",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/pg.png",
  //   name: "Pico-Gram",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/PicoGram",
  //   live: "https://smrnjeet-picogram.web.app/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/BLENDER/master/Abstract_Design/Abstract.png",
  //   name: "Blender",
  //   ext: "models",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/BLENDER",
  //   live: "https://smrnjeet222.github.io/BLENDER/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/worldRanks.png",
  //   name: "WorldRanks",
  //   ext: "tsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/WorldRanks",
  //   live: "https://world-ranks-smrnjeet222.vercel.app/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Unity_Gamedevelopment/master/MYGAME.png",
  //   name: "Unity Games",
  //   ext: "c#",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/Unity_Gamedevelopment",
  //   live: "https://smrnjeet-22.itch.io/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/background.gif",
  //   name: "NoJs-TicTacToe",
  //   ext: "css",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/noJs-TicTacToe",
  //   live: "https://codepen.io/smrnjeet222/full/gOLjOXM",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Automail.png",
  //   name: "AutoMail",
  //   ext: "py",
  //   lang: "py",
  //   git: "https://github.com/smrnjeet222/AutoMail",
  //   live: "https://github.com/smrnjeet222/AutoMail",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Unity_Gamedevelopment/master/FreakyFrog/best.png",
  //   name: "Freaky Frog",
  //   ext: "c#",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/Unity_Gamedevelopment",
  //   live: "https://smrnjeet-22.itch.io/freaky-frog",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Astar.png",
  //   name: "A*Pathfinding",
  //   ext: "py",
  //   lang: "py",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/A-star",
  //   live: "https://repl.it/@smrnjeet222/Astar#main.py",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/Space-invaders/Sc.jpg",
  //   name: "Space-invaders",
  //   ext: "py",
  //   lang: "py,games",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/Space-invaders",
  //   live: "https://github.com/smrnjeet222/Python_Apps/tree/master/Space-invaders",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Rc.png",
  //   name: "Ray Casting",
  //   ext: "js",
  //   lang: "js",
  //   git: "https://editor.p5js.org/smrnjeet222/collections/fvtHa48dt",
  //   live: "https://editor.p5js.org/smrnjeet222/sketches/j06TXs4ZF",
  // },
];
